name: CI
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  ROS_DISTRO: humble

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code from current branch
      uses: actions/checkout@v4
    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.7
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo rosdep update --rosdistro ${{ env.ROS_DISTRO }}
        sudo rosdep install --from-paths . --ignore-src -y -t test --rosdistro ${{ env.ROS_DISTRO }}
    - name: Run pre-commit
      run: |
        pip3 install pre-commit
        source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
        pre-commit run --all-files

  build_and_test:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from current branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build in Docker container
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile
        push: false
        load: true
        tags: mujoco_ros2_control:latest
    - name: Test in Docker container
      run: docker run --entrypoint "/bin/bash" --rm mujoco_ros2_control:latest -c "colcon test && colcon test-result --verbose"
